CC := vc +aos68k
CFLAGS := -c99
LIBS := -lauto -lamiga

OBJS := yfacts.o debug.o
DEPS := error.h module.h debug.h

all: yfacts

%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) -c -o $@ $<

yfacts: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)
