CC := vc +aos68k
CFLAGS := -c99 -Inetinclude
LIBS := -lauto -lamiga

OBJS := mrwolf.o debug.o sntp.c
DEPS := error.h module.h debug.h sntp.h

all: Mr.Wolf.OS3

%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) -c -o $@ $<

Mr.Wolf.OS3: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)
