CC := vc +aosppc
CFLAGS := -D__USE_INLINE__
LIBS := -lauto

OBJS := mrwolf.o timesync.o debug.o sntp.o tzlib.o ipapi.o strdup.o
DEPS := error.h module.h timesync.h debug.h sntp.h tzlib.h ipapi.h strdup.h

all: Mr.Wolf

%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) -c -o $@ $<

Mr.Wolf: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)
