on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build_ppc:
    runs-on: ubuntu-latest
    container:
      image: amigadev/crosstools:ppc-amigaos
    name: build_os4
    steps:
      - uses: actions/checkout@v2
      - name: build_os4
        id: build_os4
        run: |
          cd ./yfacts
          make -f Makefile
      - uses: actions/upload-artifact@v2
        with:
          name: yfacts
          path: ./yfacts/yfacts
  build_68k:
    runs-on: ubuntu-latest
    container:
      image: amigadev/crosstools:m68k-amigaos
    name: build_os3
    steps:
      - uses: actions/checkout@v2
      - name: build_os3
        id: build_os3
        run: |
          cd ./yfacts
          make -f Makefile.OS3
      - uses: actions/upload-artifact@v2
        with:
          name: yfacts.OS3
          path: ./yfacts/yfacts
